phasorpy/phasorpy

- pyproject.toml
- src/phasorpy/_utils.py
- src/phasorpy/phasor.py
- src/phasorpy/plot.py
- tests/test_phasor.py
- tutorials/phasorpy_introduction.py
- tutorials/phasorpy_phasorplot.py
This PR improves some parameter type annotations. It also adds few missing test cases and minor corrections to tutorials.
```release-note
Improve typing
```
> Improve typing

- requirements_dev.txt
- src/phasorpy/_phasor.pyx
Fix linting errors in Cython code. Also add [cython-lint](https://pypi.org/project/cython-lint/) to the development requirements.
```release-note
Fix linting errors in Cython code
```
> Fix linting errors in Cython code

- docs/phasor_approach.rst
Mention napari-live-flim
```release-note
Mention napari-live-flim
```
> Mention napari-live-flim

- docs/phasor_approach.rst
Mention HySP software
```release-note
Mention HySP software
```
> Mention HySP software

- docs/phasor_approach.rst
Mention [FLIMfit](https://flimfit.org/) software.
```release-note
Mention FLIMfit software
```
> Mention FLIMfit software

- docs/code_of_conduct.rst
Fix spelling
```release-note
Fix spelling
```
> Fix spelling

- docs/phasor_approach.rst
Mention [HORIBA EzTime software](https://www.horiba.com/int/scientific/products/detail/action/show/Product/eztime-software-6283) and fix duplicate explicit target names.
```release-note
Mention EzTime software
```
> Mention HORIBA EzTime software

- tutorials/phasorpy_components.py
- tutorials/phasorpy_phasor_from_lifetime.py
- tutorials/phasorpy_phasorplot.py
This PR adds initialization of random number generators with a constant value to the tutorials. It keeps plots from changing each time a tutorial is run and reduces changes in the [phasorpy.github.io](https://github.com/phasorpy/phasorpy.github.io) repository.
```release-note
Seed random number generator with constant in tutorials
```
> Seed random number generator with constant in tutorials

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/cursors.py
- tests/test__phasorpy.py
- tests/test_cursors.py
- tutorials/phasorpy_cursors.py
This PR proposes improvements to the cursors module added in #48 :
- Add common blend mode ufuncs to the `_phasorpy.pyx` Cython module.
- Various improvements to docstrings and typing.
- Update cursors tutorial with new features.
- Remove `axis` parameter from all functions to simplify API, implementation, and documentation.
- Improve `mask_from_circular_cursor` function:
- Base implementation on `_is_inside_circle` ufunc added in #81.
- Improve `mask_from_polar_cursor` function:
- Base implementation on `_is_inside_polar_rectangle` ufunc added in #81.
- Change polar coordinate input parameters to phasor coordinates to make the API consistent with `mask_from_circular_cursor`.
- Use separate parameters for min and max ranges to match ufunc and other function APIs.
- Improve `pseudo_color` …
> Improve cursors module

- tutorials/phasorpy_lfd_workshop.py
This tutorial is a close adaptation of the [LFD Workshop computer training tutorial - FLIM section](https://www.lfd.uci.edu/workshop/2021/files/LFDWorkshop2021-ComputerTraining.pdf) (by E. Gratton, M. Digman, and J. Unruh) using the PhasorPy library instead of the [Globals for Images · SimFCS](https://www.lfd.uci.edu/globals/) and Excel software.
I was curious how much of the original tutorial could be implemented using the current state of the PhasorPy library. 
The following functionality is still missing from PhasorPy to finish the tutorial:
```release-note
Add LFD workshop FLIM tutorial
```
> Add LFD workshop FLIM tutorial

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/phasor.py
- tests/test_phasor.py
- tutorials/phasorpy_lfd_workshop.py
- tutorials/phasorpy_lifetime_to_signal.py
This PR makes several additions/changes to the `phasor` and `_phasorpy.pyx` modules:
- Add `lifetime_to_signal` function, which generates time/frequency-domain decay/waveforms from specified lifetimes. The signals are convoluted with an instrument response function.
- Add `phasor_to_complex`, `phasor_multiply`, and `phasor_divide` helper functions (originally proposed in #92).
- Add private Cython functions to `_phasorpy.pyx`: `_gaussian_signal`, `_phasor_multiply`, and `_phasor_divide`.
- Rename some functions such that the phasor module only contains function names starting with `phasor_`, `polar_`, and `lifetime_`:
- `frequency_from_lifetime` -> `lifetime_to_frequency`
- `frequency_to_lifetime` -> `lifetime_from_frequency`
- `fraction_from_amplitude` -> …
> Add lifetime_to_signal function

- src/phasorpy/_utils.py
This PR fixes undefined and not defined function names in the `__all__` statement from `_utils` module.
```release-note
Fix definitions of functions in `_utils`.
```
> Fix undefined and not defined function names in `_utils`.

- README.md
- docs/acknowledgments.rst
See https://github.com/chanzuckerberg/open-science?tab=readme-ov-file#about-this-project
```release-note
Add EOSS badge and use recommended language
```
> Add EOSS badge and use recommended language

- docs/api/index.rst
This PR increases the API documentation toctree depth, such that all library function and methods are listed in the main API table of contents. Currently class methods and private functions are not listed.
```release-note
Increase API documentation toctree depth
```
> Increase API documentation toctree depth

- docs/phasor_approach.rst
[FLIMPA](https://github.com/SofiaKapsiani/FLIMPA) is an open-source GUI software designed for the phasor plot analysis of raw TCSPC-FLIM data. The software is written in Python and distributed under the BSD-3-Clause license.
```release-note
Mention FLIMPA software
```
> Mention FLIMPA software

- .github/pull_request_template.md
- .github/workflows/deploy-docs.yml
- README.md
Publish documentation in docs subfolder.
```release-note
Publish docs in subfolder
```
> Publish docs in subfolder

- README.md
- pyproject.toml
[release notes](https://www.phasorpy.org/docs/stable/release.html):
```release-note
Add links to PyPI and Zenodo to readme
```
> Add links to PyPI and Zenodo to readme

- README.md
- docs/acknowledgments.rst
- docs/index.rst
- pyproject.toml
Update project URLs.
[release notes](https://www.phasorpy.org/docs/stable/release.html):
```release-note
Update project URLs
```
> Update project URLs

- docs/_static/switcher.json
The `switcher.json` file is a prerequisite for [documentation version switcher dropdowns](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html), which will be added in a later PR.
> Add documentation version switcher config file

- docs/phasor_approach.rst
The [FLUTE license](https://github.com/LaboratoryOpticsBiosciences/FLUTE?tab=BSD-3-Clause-1-ov-file#readme) changed from GPL to BSD 3-Clause.
> Update FLUTE license

- docs/phasor_approach.rst
Mention [PhasorPlots for dummies](https://github.com/Jalink-lab/phasor-plots) in the documentation.
> Mention PhasorPlots for dummies

- docs/phasor_approach.rst
Mention [AlliGator](https://alligator-distribution.readthedocs.io) software.
> Mention AlliGator software

- tools/sha256.py
Add tool to print SHA256 hashes of dataset files.
> Add tool to print SHA256 hashes of dataset files

- docs/phasor_approach.rst
Mention Lambert's [LIFA software](https://lambertinstruments.com/lifa-software).
> Mention LIFA software

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/utils.py
- tests/test_utils.py
This PR implements the spectral vector denoising algorithm as suggested in #142 and adds a `spectral_vector_denoise` function to the public API. 
The algorithm is described in
- Rebecca C. Harman, Ryan T. Lang, Eric M. Kercher, Paige Leven, and Bryan Q. Spring. **Denoising multiplexed microscopy images in n-dimensional spectral space**. Biomedical Optics Express Vol. 13, Issue 8, pp. 4298-4309 (2022). https://doi.org/10.1364/BOE.463979
Items to discuss:
- Only denoising in Fourier space is implemented. Implementing Chebyshev transform seems out of scope of the PhasorPy library. However, any spectral vector can be passed to the `spectral_vector_denoise` function by the user.
-  Unmixing the denoised signal using least squares fit is not implemented. Again, it seems out of scope of the …
> Add spectral vector denoising

- docs/phasor_approach.rst
Mention [GSLab](https://figshare.com/articles/software/GSLab_Open-Source_Platform_for_Advanced_Phasor_Analysis_in_Fluorescence_Microscopy/27921966) software.
> Mention GSLab software

- docs/phasor_approach.rst
Mention [BrightEyes](https://github.com/VicidominiLab) software.
> Mention BrightEyes software

- .github/workflows/run-tests.yml
Static code analysis currently fails with numpy 2.2.0. Pin numpy<2.2.0 for now.
Closes #158
> Pin numpy<2.2.0 for static code analysis

- src/phasorpy/_utils.py
Fix CI failure with black 25.1.
> Reformat with black 25.1

- src/phasorpy/datasets.py
Add dataset from [zenodo.org/records/14860228](https://zenodo.org/records/14860228) and https://github.com/phasorpy/phasorpy-data/tree/main/zenodo_14860228.
> Add dataset from zenodo.org/records/14860228

- docs/api/index.rst
- docs/index.rst
- docs/release.rst
Remove notes about early stage of development.
> Remove notes about early stage of development

- src/phasorpy/plot.py
- tests/test_plot.py
- tutorials/api/phasorpy_components.py
- tutorials/api/phasorpy_io.py
This PR adds a trivial `plot_histograms` function to the `phasorpy.plot` module. It simplifies the `phasorpy_components` and `phasorpy_io` tutorials.
> Add plot_histograms function

- src/phasorpy/_utils.py
- src/phasorpy/components.py
- src/phasorpy/datasets.py
- src/phasorpy/plot.py
- src/phasorpy/utils.py
- tests/test_plot.py
- tutorials/api/phasorpy_cursors.py
- tutorials/api/phasorpy_filtering.py
- tutorials/phasorpy_introduction.py
This PR adds a `plot_image` function to the `phasorpy.plot` module. It is used to simplify plotting images in the tutorials.
Also fixes some docstring formatting.
> Add plot_image helper function

- tutorials/api/phasorpy_io.py
Demonstrate that `phasorpy.io` functions are not required to read phasor related data from files.
> Add section on other means to IO tutorial

- src/phasorpy/_io.py
- src/phasorpy/_phasorpy.pyx
- src/phasorpy/_utils.py
- src/phasorpy/color.py
- src/phasorpy/components.py
- src/phasorpy/cursors.py
- src/phasorpy/datasets.py
- src/phasorpy/phasor.py
- src/phasorpy/plot.py
- src/phasorpy/utils.py
- src/phasorpy/version.py
- tests/test_phasor.py
- tests/test_plot.py
- tutorials/api/phasorpy_components.py
- tutorials/api/phasorpy_filtering.py
- tutorials/api/phasorpy_fret.py
- tutorials/api/phasorpy_multi-harmonic.py
- tutorials/api/phasorpy_phasorplot.py
- tutorials/phasorpy_introduction.py
- tutorials/phasorpy_lfd_workshop.py
This PR addresses some minor issues found by GitHub Copilot. It mainly improves consistency, spelling, and grammar of documentation and variable naming.
> Fix minor issues found by GitHub Copilot

- docs/phasor_approach.rst
> Update description of AlliGator software

- .github/workflows/build_sdist.yml
- pyproject.toml
- requirements_dev.txt
[Cython 3.1.0](https://github.com/cython/cython/releases/tag/3.1.0) is released.
> Cython 3.1.0 is released

- tests/io/_conftest.py
- tests/io/test_ometiff.py
- tests/io/test_other.py
- tests/test_cli.py
- tests/test_datasets.py
Skip more tests if SKIP_FETCH environment variable is set.
> Skip more tests if SKIP_FETCH environment variable is set

- .github/workflows/deploy-docs.yml
- .github/workflows/run-tests.yml
Update Python versions used in workflows. Build docs with Python 3.13.
> Update Python versions used in workflows

- tutorials/api/phasorpy_io.py
> Fix io tutorial

- tutorials/applications/phasorpy_component_fit.py
Fix multi-component fit tutorial.
> Fix multi-component fit tutorial

- .github/workflows/build_wheels.yml
- .github/workflows/run-tests.yml
- pyproject.toml
Build wheels for Python 3.14. For now, skip thread-safe build and testing because not all dependencies are available yet.
> Build wheels for Python 3.14

- src/phasorpy/plot/_functions.py
- src/phasorpy/plot/_lifetime_plots.py
- src/phasorpy/plot/_phasorplot.py
- src/phasorpy/plot/_phasorplot_fret.py
- tests/plot/test_phasorplot.py
- tutorials/api/phasorpy_phasorplot.py
- tutorials/phasorpy_introduction.py
This PR improves the `PhasorPlot.polar_grid` method:
- Add optional `angles` and `radii` parameters to `PhasorPlot.polar_grid` method to specify the angular and radial grid lines drawn.
- Add optional `labels`, `ticks`, and `tick_limits` parameters to `PhasorPlot.polar_grid` method to specify text labels and ticks on unit circle.
- Add optional `samples` parameters to `PhasorPlot.polar_grid` method to specify the number of vertices of a polygon drawn inscribed in the unit circle. This is useful, for example, for RGB phasors with three samples.
- Add optional `pad` parameter to `PhasorPlot` to easily add space for labels.
- Allow the `PhasorPlot` `grid` parameter to be a dictionary of keyword arguments passed to `PhasorPlot.polar_grid`.
- Draw all angular gridlines in minor style because …
> Improve PhasorPlot.polar_grid method

- src/phasorpy/io/_leica.py
- tutorials/api/phasorpy_io.py
Document that Leica LIF files contain "Fast FLIM" lifetimes, which are average photon arrival times.
> Document that LIF files contain Fast FLIM lifetimes

- src/phasorpy/__init__.py
> Bump version

- docs/phasor_approach.rst
Mention [napari-phasors](https://github.com/napari-phasors/napari-phasors) software.
> Mention napari-phasors software
