- docs/api/datasets.rst
- docs/api/index.rst
- docs/api/io.rst
- docs/contributing.rst
- docs/index.rst
- pyproject.toml
- requirements_dev.txt
- src/phasorpy/_typing.py
- src/phasorpy/conftest.py
- src/phasorpy/datasets.py
- src/phasorpy/io.py
- src/phasorpy/version.py
- tests/test_datasets.py
- tests/test_io.py
This PR adds two new modules to the phasorpy library:
1. ``datasets``  provides a ``fetch`` function to automatically download sample data files from the [PhasorPy community repositories on Zenodo](https://zenodo.org/communities/phasorpy/). 
2. ``io`` provides functions to read time-resolved and hyperspectral image data and metadata from many file formats used in bio-imaging. This version includes readers for LSM, IFLI, SDT, and SimFCS formats. There are also convenience functions to read and write phasor coordinates (dc, re, im) to OME-TIFF (not sure how useful they are).
The PR adds new dependencies:
1. [Pooch](https://pypi.org/project/pooch/) is a lightweight package for managing sample files in remote repositories. Pooch is used by Scipy, scikit-image, and other related projects.
2. …
> Add io and datasets modules

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/run-tests.yml
- docs/acknowledgments.rst
- docs/api/cli.rst
- docs/api/datasets.rst
- docs/contributing.rst
- pyproject.toml
- requirements_dev.txt
- src/phasorpy/cli.py
- src/phasorpy/datasets.py
- src/phasorpy/io.py
- src/phasorpy/version.py
- tests/test_cli.py
- tests/test_datasets.py
This PR adds datasets from the [FLUTE](https://zenodo.org/record/8046636) and [napari-flim-phasor-plotter](https://github.com/zoccoler/napari-flim-phasor-plotter/tree/main/src/napari_flim_phasor_plotter/data) projects and enables downloading multiple or all sample files at once via the `datasets.fetch` function or `python -m phasorpy fetch` command.
The PR introduces [tqdm](https://github.com/tqdm/tqdm) as new dependency, a popular and lightweight library to display progress bars for command line apps.
> Add datasets and enable mass downloads

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
- docs/contributing.rst
This PR improves the contributing guide (especially wrt. unit test requirements) and adds a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) with a checklist.
> Improve contributing guide and create PR template

- .github/dependabot.yml
- .gitignore
See [Enabling Dependabot version updates for actions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#enabling-dependabot-version-updates-for-actions).
> Enable Dependabot version updates for actions

- .gitignore
- docs/phasor_approach.rst
- pyproject.toml
- requirements_dev.txt
- src/phasorpy/_typing.py
- src/phasorpy/io.py
- tests/test_io.py
This PR adds read functions for PTU, FBD, and FLIF files to the `phasorpy.io` module. It also fixes the IFLI spectral axes code and makes `read_sdt` accept SDT FCS data files.
The [ptufile](https://github.com/cgohlke/ptufile) library is added as an optional dependency required for reading PTU files.
Partly addresses issue #10.
```release-note
Add read functions for PTU, FBD, and FLIF files
```
> Add read functions for PTU, FBD, and FLIF files

- src/phasorpy/plot.py
- tests/test_plot.py
Somehow ``PhasorPlot.semicircle`` changed the axes limits, so re-apply the limits at the end of the method.
```release-note
Fix PhasorPlot.semicircle changes axes limits
```
> Fix PhasorPlot.semicircle changes axes limits

- src/phasorpy/plot.py
- tests/test_plot.py
Fix contour coordinates are offset by half a pixel in each direction.
```release-note
Fix contour offsets
```
> Fix contour offsets

- docs/conf.py
This PR proposes to remove type annotations/hints from the autogenerated API documentation using the [autodoc_typehints](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_typehints) setting.
Typehints can be distracting and are repeated in numpy docstrings anyways. If needed, the typehints are one click away in the `[source]` link. Here's a comparison of ``PhasorPlot.semicircle`` method with and without typehints:
---
```release-note
Hide typehints in API documentation
```
> Hide typehints in API documentation

- src/phasorpy/phasor.py
This PR adds the `skip_axes` parameter to `phasor_calibrate` function for the center calculation of reference coordinates.
...
```release-note
Add `skip_axes` parameter to `phasor_calibrate`
```
> Add `skip_axes` to `phasor_calibrate`

- src/phasorpy/io.py
- tests/test_io.py
Return number of bins in one period (1/frequency) by default.
Requires ptufile >= 2024.2.20.
```release-note
Add dtime parameter to read_ptu function
```
> Add dtime parameter to read_ptu function

- src/phasorpy/_phasor.pyx
- src/phasorpy/phasor.py
- src/phasorpy/plot.py
- tests/test_phasor.py
- tutorials/phasorpy_fret.py
- tutorials/phasorpy_phasor_from_lifetime.py
- tutorials/phasorpy_phasorplot.py
This PR adds two functions to the `phasorpy.phasor` module:
- `phasor_from_fret_donor`: Calculate phasor coordinates of a FRET donor channel as a function of frequency, donor lifetime, FRET efficiency, fraction of donors undergoing FRET, and background fluorescence.
- `phasor_from_fret_acceptor`: Calculate phasor coordinates of a FRET acceptor channel as a function of frequency, donor and acceptor lifetimes, FRET efficiency, fraction of donors undergoing FRET, fraction of directly excited acceptors, fraction of donor channel in acceptor channel, and background fluorescence.
A new tutorial, `phasorpy_fret.py`, is included.
The functionality is inspired by the [SimFCS](https://www.lfd.uci.edu/globals/) FRET calculator and the [vLFD lifetime …
> Add phasor_from_fret functions

- docs/contributing.rst
Numpy's [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) is superseded by the [Scientific Python SPEC 0 — Minimum Supported Dependencies](https://scientific-python.org/specs/spec-0000/) guideline.
Also mention the [Scientific Python development guide](https://learn.scientific-python.org/development/), which competes (?) with the [pyOpenSci Python Package Guide](https://www.pyopensci.org/python-package-guide).
The Scientific Python project provides a [repo-review](https://learn.scientific-python.org/development/guides/repo-review/?repo=phasorpy%2Fphasorpy&branch=main) tool, which we might want to check.
```release-note
Use Scientific Python …
```
> Use Scientific Python SPEC0 instead of NEP29

- docs/conf.py
- src/phasorpy/_phasor.pyx
- src/phasorpy/cli.py
- src/phasorpy/phasor.py
- src/phasorpy/plot.py
- tests/test_cli.py
- tests/test_phasor.py
- tests/test_plot.py
- tutorials/phasorpy_fret.py
This PR proposes the following changes:
- add a `PhasorPlotFret` class, which plots FRET efficiency trajectories of donor and acceptor channels in phasor space. The class can be run in interactive mode, using matplotlib slider widgets to control FRET model parameters.
- add a command line option to run `PhasorPlotFret` in interactive mode: `python -m phasorpy fret`
- simplify the `phasorpy_fret.py` tutorial using `PhasorPlotFret`. Mark the actual phasor coordinates of the donor and acceptor channels.
- add a mouse cursor callback function to `PhasorPlot`, which displays (in the matplotlib toolbar) polar coordinates and apparent lifetimes (if possible) in addition to phasor coordinates.
- rename `acceptor_excitation` to `acceptor_bleedthrough`.
- change the definition of …
> Add interactive FRET phasor plot

- src/phasorpy/plot.py
- tests/test_plot.py
- tutorials/phasorpy_phasorplot.py
This PR adds a `cursor` method to the `PhasorPlot` class. It's a simple convenience wrapper of `PhasorPlot.polar_cursor()`, accepting phasor coordinates instead of polar coordinates.
Also fixes a bug in the `PhasorPlot.polar_cursor` method drawing circles in the third quadrant, found in #48.
```release-note
Add PhasorPlot.cursor method
```
> Add PhasorPlot.cursor method

- src/phasorpy/plot.py
- tutorials/phasorpy_phasor_from_lifetime.py
Demonstrate that the average phasor coordinates for wider distributions of lifetimes lie further inside the universal semicircle compared to the narrower distributions.
Use gamma distributions for lifetimes. 
Make the lifetimes and frequencies used throughout the tutorial more consistent.
```release-note
Improve phasor_from_lifetime tutorial
```
> Improve phasor_from_lifetime tutorial

- docs/phasor_approach.rst
- src/phasorpy/phasor.py
- tests/test_phasor.py
This PR adds two utility functions to the `phasor` module:
- `frequency_from_lifetime`: Return optimal frequency for resolving single component lifetime.
- `frequency_to_lifetime`: Return single component lifetime best resolved at frequency.
I added the functions to the `phasor` module for now since we plan to move a bunch of functions from this module into a `lifetime` module or a flat namespace...
```release-note
Add functions to convert optimal frequency and lifetime
```
> Add functions to convert optimal frequency and lifetime

- setup.py
- src/phasorpy/_phasorpy.pyx
- src/phasorpy/phasor.py
- tests/test_phasor.py
Add two helper functions to the `phasor` module to convert between lifetime fractional intensities and pre-exponential amplitudes. These functions will probably be moved to a `lifetime` module at some point.
Also rename the Cython extension module from `_phasor` to `_phasorpy` since it will contain functions not related to the `phasor` module.
```release-note
Add functions to convert between lifetime fractions and amplitudes
```
> Add functions to convert between lifetime fractions and amplitudes

- .github/workflows/build_wheels.yml
- .github/workflows/run-tests.yml
- setup.py
Even though `CIBW_BEFORE_BUILD` and `CIBW_BEFORE_TEST` were set to install `numpy >= 2.0.0rc1` in #61, the wheels are neither built nor tested with numpy 2.0.0rc1 in CI. The environment variable `PIP_PRE=1` needs to be set, otherwise pip downgrades to the latest 1.x release.
```release-note
Build with NumPy 2
```
> WIP: Build with NumPy 2

- .github/workflows/run-tests.yml
- docs/contributing.rst
- requirements_dev.txt
- src/phasorpy/_utils.py
- src/phasorpy/components.py
- src/phasorpy/phasor.py
This PR applies [black](https://github.com/psf/black) formatting to docstring examples using [blackdoc](https://github.com/keewis/blackdoc) (a new development dependency). It also adds a check to the GitHub Action tests.
```release-note
Format docstring examples with blackdoc
```
> Format docstring examples with blackdoc

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/phasor.py
- tests/conftest.py
- tests/test_phasor.py
This PR adds a convenience function, `phasor_at_harmonic`, which calculates, given the real component of phasor coordinates of a single exponential lifetime at a certain harmonic, the phasor coordinates at other harmonics. It is implemented as a numpy ufunc in Cython.
```release-note
Add phasor_at_harmonic function
```
> Add phasor_at_harmonic function

- .github/workflows/build_wheels.yml
- .github/workflows/run-tests.yml
Numpy 2 was released today. No need to use pre-releases to build phasorpy wheels.
> Numpy 2 is released

- src/phasorpy/datasets.py
- tests/test_datasets.py
This PR enables GitHub Actions to use data files from the new [phasorpy-data](https://github.com/phasorpy/phasorpy-data) repository instead of [Zenodo](https://zenodo.org/communities/phasorpy).
This should make GitHub Actions a little faster and more reliable. 
Some third-party data files used during testing and in tutorials remain on Zenodo.
The "official" source of the data files remains on Zenodo.
```release-note
Use phasorpy-data repo instead of Zenodo in GitHub Actions
```
> Use phasorpy-data repo instead of Zenodo in GitHub Actions

- .codecov.yml
- .github/workflows/coverage.yml
- docs/contributing.rst
- pyproject.toml
This PR enables [code coverage](https://en.wikipedia.org/wiki/Code_coverage) reports via [Codecov](https://about.codecov.io/) for all pull requests and pushes to the main branch. 
Code coverage reports were previously generated automatically during pytest runs, but I don't think they got much attention.
```release-note
Enable code coverage via codecov.io
```
> Enable code coverage via codecov.io

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/cursors.py
- src/phasorpy/plot.py
- tests/test_cursors.py
- tests/test_plot.py
- tutorials/phasorpy_cursors.py
- tutorials/phasorpy_phasorplot.py
This PR adds support for elliptic cursors to the `plot.PhasorPlot.cursor` method and the `cursors` module. Tests and tutorials are updated.
Items to discuss:
```release-note
Add elliptic cursors
```
> Add elliptic cursors

- src/phasorpy/phasor.py
Fix type of harmonic parameter in phasor_to_signal.
```release-note
Fix type of harmonic parameter in phasor_to_signal
```
> Fix type of harmonic parameter in phasor_to_signal

- pyproject.toml
- requirements_dev.txt
- src/phasorpy/_phasorpy.pyx
Cython 3.0.11 was released today, which allows to return fused types from Cython ufuncs. Calling `numpy.import_array` and `numpy.import_ufunc` at the top of the module is no longer necessary.
Unfortunately there's a [new issue](https://github.com/cython/cython/issues/6328), which prevents from using fused types in functions returning more than 2 values. Using [typedefs in ufuncs](https://github.com/cython/cython/pull/6196) will be supported in Cython 3.1.
```release-note
Use Cython>=3.0.11
```
> Use Cython>=3.0.11

- src/phasorpy/phasor.py
- tests/test_phasor.py
While unifying the `phasor_from_signal` and `phasor_from_signal_fft` functions, I noticed that the introduction tutorial failed to calibrate phasor coordinates. `phasor_from_signal_fft` returns `NaN` when DC values are zero, which could not be handled correctly by `phasor_calibrate`. This PR changes the `phasor_center` functions to use `numpy.nanmean` and `numpy.nanmedian` instead of `numpy.mean` and `numpy.median`. I do not know if/how much slower the NaN handling is.
```release-note
Fix phasor_center with NaN input
```
> Fix phasor_center with NaN input

- src/phasorpy/plot.py
- tests/test_plot.py
This PR fixes two RuntimeWarning when using `plot_phasor_image` with images containing `NaN`:
```
phasorpy\plot.py:1753: RuntimeWarning: Mean of empty slice
real = numpy.nanmean(real.reshape(nh, -1, *real.shape[-2:]), axis=1)
phasorpy\plot.py:1754: RuntimeWarning: Mean of empty slice
imag = numpy.nanmean(imag.reshape(nh, -1, *imag.shape[-2:]), axis=1)
```
```release-note
Fix RuntimeWarning in plot_phasor_image
```
> Fix RuntimeWarning in plot_phasor_image

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/phasor.py
- tests/test_phasor.py
- tutorials/benchmarks/phasorpy_phasor_from_signal.py
This PR merges the `phasor_from_signal` and `phasor_from_signal_fft` functions into one:
- Remove `phasor_from_signal_fft` function.
- Add two parameters to `phasor_from_signal`: `use_fft` and `rfft` (used to be `rfft_func`). By default, FFT is automatically used when all or at least 8 harmonics are calculated, or a `rfft` function is specified.
- Change `irfft_func` parameter to `irfft` in `phasor_to_signal`.
- Change Cython implementation to return `NaN` or `Inf` instead of 0.0 in case of zero DC.
- Document that zero phasor coordinates are legit and phasor coordinates are undefined for zero DC.
- Update tests.
- Update benchmark tutorial.
The introduction tutorial is currently failing due to #96 and #97
[release …
> Unify phasor_from_signal functions

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/components.py
- src/phasorpy/cursors.py
- src/phasorpy/phasor.py
- tests/test__phasorpy.py
- tests/test_nan.py
- tests/test_plot.py
- tutorials/phasorpy_lfd_workshop.py
This PR is following up on #88, which settled on representing invalid or threshold-ed phasor coordinates as `NaN` (a special floating point number):
- Many Cython ufuncs now return NaN if certain input values (such as phasor or polar coordinates, or apparent single lifetimes)  are NaN. 
- The unused `mask` parameter was removed from `_is_` functions. 
- The behavior of `phasor_filter` is currently undefined (#87). 
- The `phasor_to_principal_plane` function does not work with NaNs.
- The behavior of `phasor_to_signal` likely depends on the FFT implementation. 
- The `phasor_from_signal` and `phasor_from_lifetime` functions remain unchanged. 
```release-note …
```
> Improve handling of NaN values

- src/phasorpy/components.py
- tests/test_components.py
This PR proposes the addition of default values for `fractions` in the `graphical_component_analysis` function in the `components` module. This was further discussed in #83, where the reasons for the proposed changes are stated. 
```Add default fractions to graphical_component_analysis
```
> Add default fractions to graphical_component_analysis

- docs/conf.py
- pyproject.toml
- src/phasorpy/io.py
- tests/test_io.py
- tests/test_phasor.py
- tutorials/api/README.rst
- tutorials/phasorpy_introduction.py
This PR proposes the following changes:
- Add functions to write and read multi-harmonic phasor coordinates to [OME-TIFF](https://ome-model.readthedocs.io/en/stable/ome-tiff/): `phasor_to_ometiff` and `phasor_from_ometiff`.
- Remove outdated `read_ometiff_phasor` and `write_ometiff_phasor` functions.
- Add "Store phasor coordinates" section to introduction tutorial.
- Use `mean`, `real`, `imag`, `phase`, and `modulation` as coordinate names instead of `dc`, `re`, `im`, `ph`, `md`. 
- Improve documentation for `io` module.
- Require tifffile >= 2024.8.24 for `write_ometiff_phasor`.
The main purpose of the new functions is to export phasor coordinates for reading via Bio-Formats into Fiji, Matlab, and other software. It is not meant as a long-term storage solution for the many limitations. …
> Support writing multi-harmonic phasors to OME-TIFF

- .github/workflows/build_wheels.yml
Not all dependencies are available or compatible yet.
```release-note
Do not test wheels on Python 3.13 for now
```
> Do not test wheels on Python 3.13 for now

- src/phasorpy/datasets.py
Add dataset from the publication "[Phasor-based multi-harmonic unmixing for in-vivo hyperspectral imaging](https://doi.org/10.1088/2050-6120/ac9ae9)" at https://zenodo.org/records/13625087.
Required by #106 
The link to `doi:10.1088/2050-6120/ac9ae9` is currently disabled. Pooch wasn't able to download from it. A [copy on GitHub](https://github.com/phasorpy/phasorpy-data/tree/main/zenodo_13625087) is used instead.
Example:
```python
from phasorpy.datasets import fetch
from phasorpy.io import read_lsm
signal = read_lsm(fetch('38_Hoechst_Golgi_Mito_Lyso_CellMAsk_404_488_561_633_SP.lsm'))  
```
```release-note
Add dataset from zenodo.org/records/13625087
```
> Add dataset from zenodo.org/records/13625087

- .github/workflows/build_wheels.yml
- .github/workflows/coverage.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/release-pypi.yml
- .github/workflows/run-tests.yml
- docs/contributing.rst
- docs/make.bat
- pyproject.toml
- requirements_dev.txt
- requirements_min.txt
- requirements_numpy.txt
Currently only numpy==1.23.5 is tested, while other requirements are always the latest versions.
This PR defines, and enables testing with, the following minimum runtime dependencies:
- Python 3.10
- numpy==1.24.4
- matplotlib==3.7.5
- pandas==2.0.3
- scipy==1.11.4
- scikit-image==0.20.0
- scikit-learn==1.2.2
- xarray==2023.4.0
- tifffile==2024.8.30
- lfdfiles==2024.5.24
- sdtfile==2024.5.24
- ptufile==2024.7.13
This list is roughly following the recommendation of [SPEC 0 — Minimum Supported Dependencies](https://scientific-python.org/specs/spec-0000/). 
The file reader libraries are all pinned to the currently latest versions. 
```release-note
Test minimum …
```
> Test minimum runtime requirements

- .gitignore
- docs/api/_private/_phasorpy.rst
- docs/api/_private/_utils.rst
- docs/api/_private/index.rst
- docs/api/index.rst
- pyproject.toml
- src/phasorpy/_phasorpy.pyx
- src/phasorpy/_typing.py
- src/phasorpy/_utils.py
- src/phasorpy/io.py
- src/phasorpy/phasor.py
- src/phasorpy/plot.py
- tests/test__utils.py
- tests/test_io.py
- tests/test_phasor.py
- tests/test_utils.py
- tutorials/phasorpy_introduction.py
- tutorials/phasorpy_lfd_workshop.py
This PR proposes several improvements mainly to the `io` module:
- Add option to specify dataset description in `phasor_to_ometiff`. Requires tifffile>=2024.8.30.
- Add a note to `phasor_to_ometiff` that the format is experimental and not meant for long-term storage.
- Add `phasor_to_simfcs_referenced` function to store phasor coordinates in SimFCS R64 format. The function writes chunked and/or padded files for dimensions not supported by the R64 format.
- Add `phasor_from_simfcs_referenced` function to directly read phasor coordinates from SimFCS REF or R64 files.
- Remove redundant `read_ref` and `read_r64` functions, which are replaced by `phasor_from_simfcs_referenced`.
- Delay import of xarray since not all functions are using xarray.
- Add private `_utils.chunk_iter` function to …
> Improve io module

- .github/workflows/run-tests.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/phasorpy/_phasorpy.pyx
- src/phasorpy/_typing.py
- src/phasorpy/_utils.py
- src/phasorpy/cli.py
- src/phasorpy/components.py
- src/phasorpy/conftest.py
- src/phasorpy/cursors.py
- src/phasorpy/datasets.py
- src/phasorpy/io.py
- src/phasorpy/phasor.py
- src/phasorpy/plot.py
- src/phasorpy/utils.py
- tests/test__phasorpy.py
- tests/test__typing.py
This PR enables stricter `mypy` checks and also tunes some `pre-commit` and `pytest` settings (follow-up #114):
- Enable mypy [strict](https://mypy.readthedocs.io/en/stable/command_line.html#miscellaneous-strictness-flags) and [warn-unreachable](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-warn-unreachable) flags.
- Exclude `phasorpy._phasorpy` and some third party packages from mypy.
- Fix errors in mypy strict mode (mostly missing types and `ignore[no-any-return]`).
- Use https://github.com/psf/black-pre-commit-mirror because it's faster.
- Do not allow prettier to always change line endings on Windows.
- Configure pre-commit.ci.
- Enable pytest to raise errors on deprecation warnings.
- Disable static code analysis on Python 3.10 because mypy strict mode fails …
> Enable mypy strict mode

- .pre-commit-config.yaml
- pyproject.toml
- src/phasorpy/plot.py
This PR sets `enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]` for mypy (suggested by [Repo-Review](https://learn.scientific-python.org/development/guides/repo-review/?repo=phasorpy%2Fphasorpy&branch=main)) and fixes a few new failures.
```release-note
Configure mypy enable_error_code
```
> Configure mypy enable_error_code

- pyproject.toml
- src/phasorpy/io.py
- tests/test_io.py
- tutorials/phasorpy_introduction.py
This PR makes the following changes to the `phasor_from_ometiff` function to improve overall consistency of the API:
- Return phasor coordinate images as numpy ndarrays, not xarrays. 
- Return an additional dict with metadata. 
- Return only the first harmonic stored in the file by default.
- Add option to return specific harmonic(s) from file.
The changes make the function more alike `phasor_from_signal` or `phasor_from_simfcs_referenced`, which return numpy arrays and the first harmonic by default. Metadata keys are matching the optional parameters of the `phasor_to_ometiff` function.
Another objective is to avoid using xarray since it is a large dependency and the metadata returned are trivial and repetitive for all returned arrays.
Summarize the changes in the code block below to be …
> Revise phasor_from_ometiff

- .github/workflows/build_sdist.yml
- Rename the `release-pypi.yml` GitHub Action workflow to `build_sdist.yml`.
- Remove building wheel with sdist (wheels are built in `build_wheels.yml`).
- Disable automatic upload to PyPI on tag (sdist and wheels will be uploaded manually for the first releases).
> Change release-pypi to build_sdist workflow

- .github/workflows/build_wheels.yml
- .github/workflows/run-tests.yml
- requirements_dev.txt
This PR enables testing wheels on Python 3.13.  Also disable scikit-image as a development dependency since wheels are not yet available for Python 3.13.
> Enable testing wheels on Python 3.13

- .github/workflows/build_wheels.yml
- .github/workflows/run-tests.yml
- docs/_static/switcher.json
- tools/build_manylinux2014.cmd
- tools/build_manylinux2014.sh
This PR enables testing and building wheels on AArch64 Linux [via QEMU](https://cibuildwheel.pypa.io/en/stable/faq/#emulation). Wheels for macOS and Windows are already built for ARM64. Not all dependencies are available on AArch64 Linux, so tests may be slow or fail.
Update: disabled building and testing in GitHub Actions because it is too slow and instead added scripts to locally build and test manylinux2014_aarch64 (or x86_64) wheels using Docker.
> Support Linux on AArch64

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/_utils.py
- src/phasorpy/io.py
- src/phasorpy/phasor.py
- tests/test__utils.py
- tests/test_io.py
- tests/test_phasor.py
This PR proposes the following changes to the private `_utils.parse_harmonic` function:
1. Replace `samples` with `harmonic_max` parameter to make the function more consistent and easier to understand.
2. Make `harmonic_max` parameter optional to allow for cases where the upper harmonics limit is unknown (as in #124).
This simplifies existing code a little.
Also added a note to the  `phasor_from_signal` function that "A minimum of `harmonic * 2 + 1` samples are required along `axis` to calculate correct phasor coordinates at `harmonic`". This is actually not verified in `parse_harmonic` and Fourier transform does return second harmonic numbers for 4 samples even though they are not correct phasor coordinates (as far as I understand). There is however a verified requirement for an absolute …
> Improve private parse_harmonic function

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/utils.py
- tests/test_utils.py
This PR adds the `anscombe_transformation` and `anscombe_transformation_inverse` functions to the public `utils` module.
The Anscombe transformation normalizes the standard deviation of noisy, Poisson-distributed data. It is [used by Leica](https://doi.org/10.1364/boe.420953) to transform un-normalized phasor coordinates to approximate standard Gaussian distributions before applying wavelet filters (see also #99).
We don't have any use for these functions yet, but they are easy to implement and might become useful when trying to understand/reproduce Leica's processing of phasor coordinates.
> Add Anscombe transformation functions

- docs/_static/switcher.json
- docs/conf.py
- docs/index.rst
- pyproject.toml
- requirements_dev.txt
This PR adds [version switcher dropdowns](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html) to the documentation. Unfortunately there is an [issue with the PyData Sphinx theme](https://github.com/pydata/pydata-sphinx-theme/issues/2002), which prevents this from being merged at this time.
> Add documentation version switcher dropdown

- src/phasorpy/datasets.py
This PR adds a dataset consisting of two FBD files, one of an image of a Convallaria slide and a second image of a Coumarine 6 solution to be used for calibration purposes.
The dataset is [stored in zenodo](https://zenodo.org/records/14026720).
...
> Add Convallaria dataset

- .github/workflows/build_wheels.yml
- .github/workflows/run-tests.yml
The macOS-12 environment is deprecated in GitHub Actions. See https://github.com/actions/runner-images/issues/10721
>  Upgrade GitHub Actions to macOS-13 environment

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/phasor.py
- tests/test_nan.py
- tests/test_phasor.py
- tutorials/api/phasorpy_multi-harmonic.py
This PR proposes the replacement of the current implementation of the median filter method in `phasorpy.phasor.phasor_filter`, which is a convenience wrapper around [`scipy.ndimage.median_filter`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.median_filter.html#scipy.ndimage.median_filter). As it was suggested in #87, this method has undefined behaviour for `NaN` values, giving inconsistent results.
There are two extra methods proposed at the moment:
- `_median_filter_2d`: based on a cython implementation of a 2D median filter. This method handles `NaN` values predictably, by ignoring them when creating the 2D-kernel for filtering. In the case a kernel has an even number of elements, the average value of the two middle elements is selected as the median, which is what …
> Replace median filter implementation for NaN handling consistency

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/phasor.py
- tutorials/phasorpy_introduction.py
This PR improves upon #147, simplifying the implementation and boosting performance of median filtering:
- Do not call `_quickselect` twice in `_median` function for even-sized kernels.
The functions are now merged into one `_median` function.
- Move "repeat" loop into `_apply_2d_median_filter` function nogil section.
- Separate "repeat" loops for real and imag to improve memory efficiency.
- Merge `_median_filter_2d` and `_median_filter_nd` into one `_median_filter` function.
- Rename `_apply_2d_median_filter` to `_median_filter_2d`.
- Use separate `nan_mask` for real and imag to match Cython implementation.
- ~Move median filter after thresholding in introductory tutorial. That should be better practice now that the median filter correctly handles NaN, no? Added a note that "filtered …
> Improve median filter

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/phasor.py
- tests/test_nan.py
- tests/test_phasor.py
- tutorials/api/phasorpy_lifetime_to_signal.py
- tutorials/api/phasorpy_multi-harmonic.py
- tutorials/phasorpy_introduction.py
- tutorials/phasorpy_lfd_workshop.py
This PR proposes several new features and breaking changes to fix issues raised in #99 and #122:
- Add `normalize` parameter to `phasor_from_signal` function.
This is a trivial change but might be useful for experimenting with filter algorithms.
- Add `phasor_normalize` function.
Use to normalize phasor coordinates returned by `phasor_from_signal(..., normalize=False)` or provided by user.
Do we need a `phasor_unnormalize` function, maybe for internal use? It's probably a good idea that no other public function should require unnormalized coordinates. Un/re-normalization can be transparently handled internally if necessary.
- Rename `phasor_filter` function to `phasor_filter_median`:
- Remove `method` parameter.
- Add `use_scipy` parameter to be used instead of `method='median_scipy'`.
- …
> Fix averaging phasor coordinates and related issues

- src/phasorpy/io.py
- tests/test_io.py
- tutorials/api/phasorpy_multi-harmonic.py
- tutorials/phasorpy_introduction.py
This PR adds a `read_imspector_tiff` function to the `phasorpy.io` module to read TCSPC image stacks and select metadata from ImSpector FLIM TIFF formatted files. The implementation is based on reverse engineering very few [data files by the FLUTE project](https://zenodo.org/records/8046636).
Closes #105.
> Add support for ImSpector FLIM TIFF files

- src/phasorpy/_utils.py
- src/phasorpy/io.py
- src/phasorpy/phasor.py
- src/phasorpy/plot.py
- tests/test__utils.py
- tests/test_io.py
- tests/test_plot.py
- tutorials/phasorpy_introduction.py
This PR adds support for passing `axis` string labels (as an alternative to integers) to the `phasor_from_signal` and `plot_signal_image` functions. The labels are used to index `xarray.DataArray` instances returned from the read functions in `phasorpy.io`.
The `axis` parameter default is changed from the last axis to 'H', 'C', or last axis (whatever is found first). 
'H' or 'C' axes coordinates in the DataArray, if any, are used for plotting.
This PR also fixes a bug in the coordinates returned by the `read_imspector_tiff` function (#105).
> Support labelled signal axes

- src/phasorpy/io.py
- tests/test_io.py
This PR attempts to normalize the units in which xarray coordinate array values are returned by the file reader functions in `phasorpy.io`:
- wavelengths: nm
- frequency: MHz
- TCSPC histogram: ns
- time: s
Note that the implementation is based on few test files and often undocumented metadata. On the other hand, the array coordinates are currently only used for plotting within the library.
> Return array coordinates from files in normal units

- README.md
- docs/index.rst
- tutorials/phasorpy_introduction.py
PhasorPy is now available on [conda-forge](https://anaconda.org/conda-forge/phasorpy). See #154
> Document availability on conda-forge

- docs/release.rst
Fixes the following pre-commit failures:
```
rst ``code`` is two backticks............................................Failed
- hook id: rst-backticks
- exit code: 1
docs/release.rst:17:It fixes the averaging of phasor coordinates in the `phasor_center` and
docs/release.rst:18:`phasor_calibrate` functions, replaces the `phasor_filter` function
docs/release.rst:19:with `phasor_filter_median`, adds support for multiple harmonics to
docs/release.rst:20:`phasor_threshold`, and adds the `read_imspector_tiff` function to read
```
> Fix RST code is two backticks

- src/phasorpy/io.py
- tests/test_io.py
This PR adds support for reading point mode PTU files, commonly used to store instrument response functions, to the `read_ptu` function.
Items to discuss:
- No public sample file is available for testing, so coverage in CI decreases.
- The T, Y, and X dimensions are prepended to the point mode TCSPC histograms to make them broadcastable with image data returned by the function. That should facilitate calibration with IRF.
- The xarray returned by the `read_ptu` function now has an additional `ptu_tags` attribute, which contains the original tags read from PTU file. I'm not sure this is a good idea as it adds support overhead, and the metadata might be out of sync with the returned data. If yes, we might want to consider returning original metadata for other read functions as well. Should …
> Support reading point mode PTU files

- pyproject.toml
- requirements_dev.txt
- src/phasorpy/datasets.py
- src/phasorpy/io.py
- src/phasorpy/phasor.py
- src/phasorpy/version.py
- tests/test_io.py
This PR adds two functions, `phasor_from_lif` and `signal_from_lif`, to `phasorpy.io`. This partly implements #17.
The implementation depends on the newly developed [`liffile`](https://github.com/cgohlke/liffile/) library, which is not quite feature complete or stable yet. However, compared to existing libraries, `readlif` and `Bio-Formats`, `liffile`'s license is MIT-compatible and the library can correctly read phasor coordinates, float16 and float32 images, and any-dimensional image data. "FLIM Compressed" raw images are not supported because the compression scheme is patent-pending.
The [FLIM testdata](https://figshare.com/articles/dataset/FLIM_testdata/22336594/1) is added to `phasorpy.datasets`.
Issues to discuss:
- No appropriate (public, small) hyperspectral LIF files (public, …
> Add support for Leica LIF files

- src/phasorpy/phasor.py
- tests/test_phasor.py
Fix the `phasor_normalize` function with `samples=1` on numpy 1.24. See #167.
> Fix phasor_normalize with numpy 1.24

- src/phasorpy/_io.py
- tests/test_io.py
Fix filling all excess space with NaN in the `phasor_to_simfcs_referenced` function.
> Fix NaN padding in phasor_to_simfcs_referenced

- src/phasorpy/_io.py
- src/phasorpy/datasets.py
- tests/test_io.py
This PR changes the IFLI and FBD readers to return more metadata, which are required to interpret the returned data:
- Return number of signal samples from `phasor_from_ifli`.
- Return harmonic of histogram as well as original FBD header and firmware settings from `signal_from_fbd`.
Also add references to underlying libraries and enable testing `signal_from_fbd` in CI.
> Return more metadata from IFLI and FBD readers

- src/phasorpy/datasets.py
- tutorials/api/phasorpy_components.py
- tutorials/api/phasorpy_cursors.py
- tutorials/api/phasorpy_io.py
This PR adds sections for several file formats to the "File input/output" tutorial:
- Zeiss LSM
- Becker & Hickl SDT
- FLIMbox FBD
- ISS IFLI
- SimFCS REF and R64
- PhasorPy OME-TIFF
Also unifies tutorials to use "`from matplotlib import pyplot`" imports.
> Add more formats to file I/O tutorial

- src/phasorpy/_utils.py
- src/phasorpy/io.py
- tests/test__utils.py
The `__module__` attributes of functions in `phasorpy.io` are corrected from `'phasorpy._io'` (private namespace) to `'phasorpy.io'` (public namespace). 
The helper function, `phasorpy._utils.set_module`, can be reused when moving `phasorpy.phasorpy.*` to the `phasorpy` namespace.
> Fix module attribute of functions in phasorpy.io

- src/phasorpy/_utils.py
- src/phasorpy/phasor.py
- tests/test__utils.py
- tests/test_phasor.py
Move the `phasor._parse_skip_axis` function to `_utils.parse_skip_axis` so it can be reused in other modules.
Required by #201.
> Move parse_skip_axis function to _utils module

- src/phasorpy/_utils.py
- src/phasorpy/cli.py
- src/phasorpy/conftest.py
- src/phasorpy/phasor.py
- src/phasorpy/version.py
numpy 2.2.4, released today, includes many fixes related to typing. This caused some new mypy errors in PhasorPy code related to the use of `numpy.atleast_1d`. This PR works around the new errors and also adds missing `__all__` attributes to modules.
> Fix new mypy errors with numpy 2.2.4

- src/phasorpy/_io.py
- tests/test_io.py
This PR adds support for up to two additional routing/detector channels to the `signal_from_sdt` functions. Since version 2025.3.25, `sdtfile` returns up to 5 dimensional data arrays if routing channels are present in SDT files.
> Support routing channels in signal_from_sdt

- src/phasorpy/plot.py
- tests/test_plot.py
This PR fixes `ValueError: Either colors or cmap must be None` if `PhasorPlot.contour` is called with a `colors` parameter.
Closes #212.
> Ignore PhasorPlot.contour cmap if colors is set

- .github/workflows/build_sdist.yml
- pyproject.toml
- requirements_dev.txt
- src/phasorpy/_phasorpy.pyx
- src/phasorpy/components.py
- tests/test_phasor.py
This PR bumps the Cython dependency to version 3.1.0b1 (released today), which fixes some long standing bugs relevant to this project:
- https://github.com/cython/cython/pull/6196#issuecomment-2209509572
- https://github.com/cython/cython/issues/6328
Workarounds for Cython<3.1 are removed. Masking operations should now be more efficient and the `phasor_threshold` output data type matches the input type. The output of the `graphical_component_analysis` is explicitly set to `uint64`.
This PR also adds a flag to signal [free-threading](https://docs.python.org/3/howto/free-threading-python.html) compatibility (tested on my Windows system).
> Require Cython>=3.1.0b1

- src/phasorpy/_io.py
- src/phasorpy/_phasorpy.pyx
- tests/test_io.py
This PR fixes reading multi-channel FLIM LABS files containing only single-channel phasor coordinates. 
A multi-channel FLIM LABS dataset was provided, where the header of the "phasor" files indicated the presence of two channels, but the files contain only phasor data for a single channel each. A ValueError was raised in that case.
> Fix multi-channel FLIM LABS files containing single-channel phasors

- src/phasorpy/version.py
Use [`importlib.metadata.version`](https://docs.python.org/3/library/importlib.metadata.html#importlib.metadata.version) to get versions of installed packages. Use package `__version__` attribute as fallback.
Fixes `DeprecationWarning: The '__version__' attribute is deprecated and will be removed in Click 9.1. Use feature detection or 'importlib.metadata.version("click")' instead.`
> Use importlib to get package versions

- src/phasorpy/cluster.py
- tests/test_cluster.py
This PR fixes the order in which clusters are returned by the `phasor_cluster_gmm` function. Clusters are now returned in sorted order, by polar coordinates (default), phasor coordinates, or inverse ellipse area.
In #235, the `test_phasor_cluster_gmm_basic[2]` test started failing because the order of clusters returned by  `phasor_cluster_gmm` changed for unknown reason.
> Sort clusters returned by phasor_cluster_gmm

- tests/io/test_leica.py
Fix a test failing with numpy 2.3.0, first noticed in #238:
```
================================== FAILURES ===================================
_________________________ test_lifetime_from_lif[lif] _________________________
format = 'lif'
@pytest.mark.skipif(SKIP_FETCH, reason='fetch is disabled')
@pytest.mark.parametrize('format', ('lif', 'xlef'))
def test_lifetime_from_lif(format):
"""Test read lifetime image from Leica LIF file."""
filename = fetch(f'FLIM_testdata.{format}')
lifetime, intensity, stddev, attrs = lifetime_from_lif(filename)
for data in (intensity, lifetime, stddev):
assert data.shape == (1024, 1024)
assert data.dtype == numpy.float32
>       assert intensity.sum() == 19278548.0
E       assert np.float32(1.9278552e+07) == 19278548.0
E        +  where …
```
> Fix test failing with numpy 2.3.0

- docs/conf.py
- src/phasorpy/_phasorpy.pyx
- src/phasorpy/components.py
- tests/test_components.py
- tutorials/api/phasorpy_components.py
- tutorials/applications/phasorpy_component_fit.py
This PR adds the `phasor_component_fit` function to the `phasorpy.components` module. 
The function implements the algebraic method to unmix spectra described in [Phasor-based multi-harmonic unmixing for in-vivo hyperspectral imaging](https://doi.org/10.1088/2050-6120/ac9ae9).
The functionality was proposed in #47 and incompletely implemented in #106. 
Compared to #106, this implementation is complete and provides tests and tutorials. The option to accept a pre-calculated `component_matrix` was removed since it complicates the API, exposes function internals, and it does not take significant time to re-create the matrix. I did not quite understand the reason for the special handling of infinite values in #106 and removed it for now.
In a followup PR, I will propose to rename the …
> Add phasor_component_fit function

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/phasor.py
- src/phasorpy/plot.py
- tests/test__phasorpy.py
- tests/test_phasor.py
- tutorials/phasorpy_lifetime_geometry.py
This PR adds the `phasor_semicircle_intersect` helper function to the `phasorpy.phasor` module. The function calculates the intersection coordinates of the universal semicircle with the lines between two sets of phasor coordinates. It is implemented as a numpy ufunc in Cython. The function could be used, for example, to calculate a second single exponential lifetime component given the phasor coordinates of a first component and a mixture of both components (see tests).
> Add phasor_semicircle_intersect function

- src/phasorpy/_phasorpy.pyx
- tests/test__phasorpy.py
This PR adds two private helper functions (implemented as numpy ufuncs in Cython) to mask phasor coordinates inside or near the universal semicircle with some tolerance:
- _is_inside_semicircle
- _is_near_semicircle
The `test_geometric_ufunc_on_grid` test now produced the following figure:
> Add private helper functions to mask universal semicircle

- src/phasorpy/_phasorpy.pyx
- tests/test__phasorpy.py
This PR adds a private `_distance_from_semicircle` function. See also #242.
> Add private _distance_from_semicircle function

- src/phasorpy/io/_simfcs.py
- tests/io/test_simfcs.py
The [FLIM and Spectral dataset for GSLab on figshare](https://figshare.com/articles/dataset/FLIM_dataset_for_GSLab/28067108) contains a `.REF` file, `Mosaic04_10x3_FOV600_z95_32A1_t06_uncalibrated.ref`, that stores non-256x256 sized images. Turns out there are [other variants of the SimFCS referenced format](https://github.com/AlexVallmitjana/GSLab/blob/0d450773861393b6a0b407a3390ee06fd706a533/scripts/refread.m#L58-L110) that contain up to 8 harmonics. The harmonics may be uncalibrated, which defeats the purpose of "referenced" files.
This PR adds support for reading such variants. Only a single test file is available. Writing such files will not be implemented. These files are incompatible with SimFCS.
Decoding `.REF` files no longer requires the `lfdfiles` library.
> Support reading variants of SimFCS referenced files

- src/phasorpy/datasets.py
This PR adds the [FLIM and spectral dataset for GSLab](https://figshare.com/articles/dataset/FLIM_dataset_for_GSLab/28067108) to the `phasorpy.datasets` module. The files are actually pulled from the [phasorpy-data](https://github.com/phasorpy/phasorpy-data/tree/main/figshare_28067108) repository for now.
> Add GSLab dataset

- .github/workflows/build_wheels.yml
- .github/workflows/run-tests.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/phasorpy/components.py
- src/phasorpy/experimental.py
This PR removes the `numpy<2.2.0` pin for static code analysis introduced in #159 (closes #158) and addresses some other maintenance issues:
- ignore two new mypy errors
- disable tests that fetch files when building wheels (this frequently caused failed tests)
- update dependencies in pre-commit
- remove deprecated `numpy.typing.mypy_plugin`
- update cibuildwheel to 3.0.1
> Remove numpy pin for static code analysis

- src/phasorpy/components.py
- tests/test_components.py
- tutorials/applications/phasorpy_component_fit.py
This PR adds a `phasor_from_component` function to the `phasorpy.components` module. The function calculates phasor coordinates from fractional intensities of components using dot product. It is useful for testing/verification and to complement the component API.
Multi-dimensional component arrays (such as would be returned by a `phasor_component_blind` function) are currently not implemented.
> Add phasor_from_component function

- src/phasorpy/_phasorpy.pyx
- src/phasorpy/_utils.py
- src/phasorpy/components.py
- src/phasorpy/phasor.py
- tests/test__utils.py
- tests/test_components.py
This PR adds a `phasor_component_mvc` function to the `phasorpy.components` module. The function calculates mean value coordinates of phasor coordinates for three or more components according to Fuda C and Hormann K. [A new stable method to compute mean value coordinates](https://doi.org/10.1016/j.cagd.2024.102310), *Computer Aided Geometric Design*, 111: 102310 (2024). The core algorithm is implemented in Cython.
For three components, this function returns the same result (the barycentric coordinates) as `phasor_component_fit`. For more than three components, the system is underdetermined and the mean value coordinates represent one of multiple solutions. However, the special properties of the mean value coordinates make them particularly useful for interpolating and visualizing …
> Add phasor_component_mvc function

- pyproject.toml
- requirements_min.txt
Drop support for numpy 1.25, conforming with [SPEC0](https://scientific-python.org/specs/spec-0000/).
> Drop support for numpy 1.25

- .github/workflows/run-tests.yml
- pyproject.toml
- src/phasorpy/_phasorpy.pyx
- src/phasorpy/lifetime.py
- tests/test_lifetime.py
This PR adds a `phasor_to_lifetime_search` function to the `phasorpy.lifetime` module.
It is an alternative implementation to #251. See also #47.
The function returns phasor coordinates and fractional intensities of two single lifetime components from a set of multi-harmonic phasor coordinates using the graphical approach described in:
Vallmitjana A, Torrado B, Dvornikov A, Ranjit S, and Gratton E. 
[Blind resolution of lifetime components in individual pixels of fluorescence lifetime images using the phasor approach](https://doi.org/10.1021/acs.jpcb.0c06946).
J Phys Chem B, 124(45): 10126-10137 (2020)
Currently only the two component graphical method is implemented. A straightforward implementation of the three component method (part of #251) was found impractical and needs to be revised …
> Add phasor_to_lifetime_search function for two components

- .github/workflows/build_wheels.yml
- .github/workflows/run-tests.yml
- pyproject.toml
Build wheels for [free-threaded Python](https://docs.python.org/3.14/howto/free-threading-python.html). Tests are currently disabled since not all dependencies are available yet for free-threaded Python:
> Build wheels for free-threaded Python

- MANIFEST.in
- tools/build_manylinux.cmd
- tools/build_manylinux.sh
This PR renames the `build_manylinux2014.*` scripts to `build_manylinux.*`to reflect that wheels are no longer built for `manylinux_2014` but `manylinux_2_17`.
> Rename build_manylinux scripts

- src/phasorpy/phasor.py
- tests/test_phasor.py
- tutorials/misc/phasorpy_phasor_from_signal.py
Update docstrings, tests, and tutorial to `mkl_fft` 2.0, which changed location of the `numpy_fft` interface.
> Update to mkl_fft 2.0
